const TelegramBot = require('node-telegram-bot-api');
const { runAnalysis } = require('../analyzer');
const { getNewsData } = require('../news');
const { runFastSignal } = require('../fast-analyzer');

const token = process.env.TELEGRAM_BOT_TOKEN;
const bot = new TelegramBot(token);

module.exports = async (req, res) => {
  if (req.method === 'POST') {
    const msg = req.body.message;
    if (msg && msg.text) {
      const chatId = msg.chat.id;
      const text = msg.text.trim();

      console.log(`[Webhook Received] ChatID: ${chatId} | Text: ${text}`);

      try {
        if (text.startsWith('/start')) {
          await bot.sendMessage(chatId,
            `Halo! Saya adalah <b>AI Trading Assistant</b> Anda.\n\nGunakan perintah berikut:\n\n` +
            `⚡ /fast — <b>Sinyal instan sekarang</b> (cepat, 1 sinyal, rules fleksibel)\n` +
            `🔍 /high — Scanning high-probability setup (analisis mendalam, RR 1:2)\n` +
            `📰 /news — Berita market &amp; crypto terbaru\n` +
            `📈 /trend — <b>Analisis Tren Sosmed</b> (Deteksi viralitas untuk marketing)\n` +
            `✅ /status — Cek status bot`,
            { parse_mode: 'HTML' }
          );
        } else if (text.startsWith('/fast')) {
          await runFastSignal(bot, chatId);
        } else if (text.startsWith('/high')) {
          await runAnalysis(bot, chatId, false);
        } else if (text.startsWith('/trend')) {
          await bot.sendMessage(chatId, '⏳ Sedang menganalisis tren industri di Indonesia via Google News...');
          const socialScanner = require('../social_scanner');
          const trendAnalyzer = require('../trend_analyzer');
          const watchlist = trendAnalyzer.watchlist;
          const articles = await socialScanner.scanKeywords(watchlist);
          const { trends, activityCount } = trendAnalyzer.analyze(articles);

          if (trends.length === 0) {
            let debugMsg = `📉 <b>INDONESIA TREND SCANNER</b>\n📅 ${new Date().toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })}\n\n`;
            debugMsg += `Tidak ditemukan lonjakan keyword signifikan di pasar Indonesia hari ini.\n\n<b>Aktivitas Terdeteksi:</b>\n`;
            Object.entries(activityCount).forEach(([kw, count]) => {
              debugMsg += `• ${kw}: ${count} mentions\n`;
            });
            debugMsg += `\n<i>Saran: Coba cek kembali dalam 12 jam ke depan.</i>`;
            await bot.sendMessage(chatId, debugMsg, { parse_mode: 'HTML' });
          } else {
            await bot.sendMessage(chatId, `🇮🇩 <b>INDONESIA TREND REPORT</b>\n📅 ${new Date().toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })}\n\n<i>Berikut adalah topik yang sedang naik daun:</i>`, { parse_mode: 'HTML' });
            for (const t of trends) {
              let trendMsg = `🔥 <b>TRENDING NOW: [${t.keyword}]</b>\n`;
              trendMsg += `Status: <b>${t.status}</b> (${t.count} berita)\n\n`;
              trendMsg += `📰 <b>Headline Terbaru:</b>\n`;
              t.articles.forEach(art => {
                trendMsg += `• "${art.title}" — <b>${art.source}</b>\n🔗 <a href="${art.link}">Baca Artikel</a>\n\n`;
              });
              trendMsg += `💡 <b>Marketing Insight (ID Market):</b>\n${trendAnalyzer.getInsight(t.keyword)}`;
              await bot.sendMessage(chatId, trendMsg, { parse_mode: 'HTML', disable_web_page_preview: false });
            }
          }
        } else if (text.startsWith('/create')) {
          const args = text.split(' ').slice(1).join(' ');
          if (!args) {
            await bot.sendMessage(chatId, '❓ <b>Keyword tidak ditemukan!</b>\n\nSilakan masukkan keyword setelah command /create.\nContoh: <code>/create AI Agent</code>', { parse_mode: 'HTML' });
          } else {
            await bot.sendMessage(chatId, `⏳ Sedang meracik script viral untuk <b>"${args}"</b>...`);
            const contentGenerator = require('../content_generator');
            const result = await contentGenerator.generateHooks(args);
            let formattedScripts = result.text.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>').replace(/\*/g, '•').replace(/#/g, '');
            await bot.sendMessage(chatId, `🎬 <b>CONTENT STRATEGY: ${args}</b>\n\n${formattedScripts}\n\n🤖 <i>Generated by: ${result.model}</i>`, { parse_mode: 'HTML' });
          }
        } else if (text.startsWith('/news')) {
          await bot.sendMessage(chatId, '⏳ Sedang menarik berita terkini...');
          const newsMessage = await getNewsData();
          await bot.sendMessage(chatId, newsMessage, { parse_mode: 'HTML', disable_web_page_preview: true });
        } else if (text.startsWith('/status')) {
          await bot.sendMessage(chatId,
            `✅ <b>Bot Active &amp; Running di Vercel Serverless</b>\nSistem siap menganalisis market kapan saja.\n\n` +
            `⚡ /fast — Sinyal instan (1 sinyal, rules longgar)\n` +
            `🔍 /high — High-probability setup (RR minimal 1:2)\n` +
            `📰 /news — Berita market &amp; crypto terbaru\n` +
            `📈 /trend — Analisis Tren Sosmed\n` +
            `🎬 /create [keyword] — Buat script konten viral`,
            { parse_mode: 'HTML' }
          );
        } else if (text.startsWith('/cek_versi')) {
          await bot.sendMessage(chatId, `🚀 <b>Sistem Terupdate!</b>\nServer Time: ${new Date().toLocaleString('id-ID')}\nStatus: Online`, { parse_mode: 'HTML' });
        }
      }
    }
  } catch (e) {
    console.error(`[Global Error] ${e.message}`);
  }
  res.status(200).send('OK');
};
